# Generated by Django 3.0.2 on 2020-01-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_dewey_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(editable=False, max_length=61),
        ),
        migrations.AlterField(
            model_name='dewey',
            name='number',
            field=models.CharField(max_length=3),
        ),
    ]
