# Generated by Django 3.0.2 on 2020-01-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200107_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='genre',
        ),
        migrations.AddField(
            model_name='publication',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
