# Generated by Django 3.0.2 on 2020-01-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200108_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='dewey',
            name='bg_color',
            field=models.CharField(default='*', max_length=7),
        ),
        migrations.AddField(
            model_name='dewey',
            name='text_color',
            field=models.CharField(default='*', max_length=7),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type_publication',
            field=models.CharField(choices=[('B', 'Livres'), ('M', 'Musique'), ('F', 'Film'), ('*', 'Autre')], default='B', max_length=1),
        ),
    ]
