# Generated by Django 3.0.2 on 2020-01-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200110_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=61, verbose_name='Ouvrage'),
        ),
    ]
