# Generated by Django 3.0.2 on 2020-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200123_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
